name: 极客学院 · 科举考试 · FizzBuzz TDD

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [8.x, 10.x, 12.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Run ESLint
      uses: stefanoeb/eslint-action@1.0.0
      with:
        args: "index.js src/**.js"
    - name: npm install, build, and test
      run: |
        npm run lint
        npm run build
        npm test
      env:
        CI: true
    - name: Jest Code Coverage Report
      uses: ziishaned/jest-reporter-action@v0.0.1
      with:
        # Github token
        github-token: ${{ secrets.ACCESS_TOKEN }}
